include: package:very_good_analysis/analysis_options.10.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    use_if_null_to_convert_nulls_to_bools: false
    require_trailing_commas: true
    avoid_catches_without_on_clauses: false

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.gen.dart"
    - "**/*.freezed.dart"
    - "**/*.graphql.dart"
    - "lib/gen/*"
    - "lib/schema.graphql"

  errors:
    invalid_annotation_target: ignore
    avoid_dynamic_calls: ignore
    use_setters_to_change_properties: ignore

formatter:
  page_width: 120
  trailing_commas: preserve
